package warisan;

import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erina 
 * Erina Devianti / 21120120140148 
 * Program Perhitungan Hak Waris
 * 
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    public void arrayTable() {
        String[][] data = {
            {"Suami", jmlSuami.getText(), txSuami.getText()},
            {"Istri", jmlIstri.getText(), txIstri.getText()},
            {"Ayah", jmlAyah.getText(), txAyah.getText()},
            {"Ibu", jmlIbu.getText(), txIbu.getText()},
            {"Anak laki-laki", jmlAnakLk.getText(), txAnakLk.getText()},
            {"Anak perempuan", jmlAnakPrm.getText(), txAnakPrm.getText()}
        };

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        for (String[] row : data) {
            model.addRow(row);
        }

//        for(int i = 0; i < data.length; i++){
//            String[] row = new String[data[i].length];
//            
//            for(int j = 0; j< data[i].length; j++){
//                row[j] = data[i][j];
//            }
//            model.addRow(row);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jButtonInfoPewaris = new javax.swing.JButton();
        jButtonAhliWaris = new javax.swing.JButton();
        jButtonTentang = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        pewarisPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbPria = new javax.swing.JRadioButton();
        rbWanita = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbMenikah = new javax.swing.JRadioButton();
        rbJomblo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtHartaWaris = new javax.swing.JTextField();
        jbtnReset1 = new javax.swing.JButton();
        jbtnLanjut1 = new javax.swing.JButton();
        ahliwarisPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rbHidup = new javax.swing.JRadioButton();
        rbTidakHidup = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        chkAnakLk = new javax.swing.JCheckBox();
        chkAnakPrm = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cmbOrtu = new javax.swing.JComboBox<>();
        btnKembali = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnTambahkan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtAnakLk = new javax.swing.JTextField();
        txtAnakPrm = new javax.swing.JTextField();
        ringkasanPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txIstri = new javax.swing.JTextField();
        txSuami = new javax.swing.JTextField();
        txAyah = new javax.swing.JTextField();
        txIbu = new javax.swing.JTextField();
        txAnakLk = new javax.swing.JTextField();
        txAnakPrm = new javax.swing.JTextField();
        jmlSuami = new javax.swing.JLabel();
        jmlIstri = new javax.swing.JLabel();
        jmlAyah = new javax.swing.JLabel();
        jmlIbu = new javax.swing.JLabel();
        jmlAnakLk = new javax.swing.JLabel();
        jmlAnakPrm = new javax.swing.JLabel();
        tentangPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perhitungan Harta Waris");
        setMaximumSize(new java.awt.Dimension(950, 600));
        setMinimumSize(new java.awt.Dimension(950, 600));
        setPreferredSize(new java.awt.Dimension(950, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        menuPanel.setBackground(new java.awt.Color(204, 255, 204));
        menuPanel.setMaximumSize(new java.awt.Dimension(242, 570));
        menuPanel.setMinimumSize(new java.awt.Dimension(242, 570));

        jButtonInfoPewaris.setBackground(new java.awt.Color(153, 204, 255));
        jButtonInfoPewaris.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButtonInfoPewaris.setText("Informasi Pewaris");
        jButtonInfoPewaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonInfoPewarisMouseClicked(evt);
            }
        });

        jButtonAhliWaris.setBackground(new java.awt.Color(255, 214, 224));
        jButtonAhliWaris.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButtonAhliWaris.setText("Informasi Ahli Waris");
        jButtonAhliWaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAhliWarisMouseClicked(evt);
            }
        });

        jButtonTentang.setBackground(new java.awt.Color(255, 239, 159));
        jButtonTentang.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButtonTentang.setText("Tentang Program");
        jButtonTentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTentangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonInfoPewaris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTentang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAhliWaris))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonInfoPewaris, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonAhliWaris, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtonTentang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(508, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        pewarisPanel.setBackground(new java.awt.Color(153, 204, 255));
        pewarisPanel.setMaximumSize(new java.awt.Dimension(680, 600));
        pewarisPanel.setMinimumSize(new java.awt.Dimension(680, 600));
        pewarisPanel.setPreferredSize(new java.awt.Dimension(710, 600));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Jenis kelamin pewaris");

        rbPria.setText("Pria");
        rbPria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPriaActionPerformed(evt);
            }
        });

        rbWanita.setText("Wanita");
        rbWanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWanitaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Apakah pewaris telah menikah secara sah?");

        rbMenikah.setText("Ya, sudah menikah");
        rbMenikah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMenikahActionPerformed(evt);
            }
        });

        rbJomblo.setText("Tidak, belum menikah");
        rbJomblo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJombloActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Total harta yang akan diwariskan");

        txtHartaWaris.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHartaWarisKeyTyped(evt);
            }
        });

        jbtnReset1.setText("Reset");
        jbtnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReset1ActionPerformed(evt);
            }
        });

        jbtnLanjut1.setText("Lanjut");
        jbtnLanjut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLanjut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pewarisPanelLayout = new javax.swing.GroupLayout(pewarisPanel);
        pewarisPanel.setLayout(pewarisPanelLayout);
        pewarisPanelLayout.setHorizontalGroup(
            pewarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pewarisPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pewarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHartaWaris, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pewarisPanelLayout.createSequentialGroup()
                        .addComponent(rbMenikah)
                        .addGap(26, 26, 26)
                        .addComponent(rbJomblo))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pewarisPanelLayout.createSequentialGroup()
                        .addComponent(jbtnReset1)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLanjut1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pewarisPanelLayout.createSequentialGroup()
                        .addComponent(rbPria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbWanita)
                        .addGap(84, 84, 84)))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        pewarisPanelLayout.setVerticalGroup(
            pewarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pewarisPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pewarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPria)
                    .addComponent(rbWanita))
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pewarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMenikah)
                    .addComponent(rbJomblo))
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHartaWaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pewarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLanjut1)
                    .addComponent(jbtnReset1))
                .addContainerGap(442, Short.MAX_VALUE))
        );

        mainPanel.add(pewarisPanel, "card2");

        ahliwarisPanel.setBackground(new java.awt.Color(255, 214, 224));
        ahliwarisPanel.setMaximumSize(new java.awt.Dimension(715, 600));
        ahliwarisPanel.setMinimumSize(new java.awt.Dimension(650, 600));
        ahliwarisPanel.setPreferredSize(new java.awt.Dimension(715, 600));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Apakah pasangan pewaris masih hidup?");

        rbHidup.setText("Ya");
        rbHidup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHidupActionPerformed(evt);
            }
        });

        rbTidakHidup.setText("Tidak");
        rbTidakHidup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTidakHidupActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Jumlah anak pewaris yang masih hidup");

        chkAnakLk.setText("Anak laki-laki");
        chkAnakLk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAnakLkActionPerformed(evt);
            }
        });

        chkAnakPrm.setText("Anak perempuan");
        chkAnakPrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAnakPrmActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Orang tua pewaris yang masih hidup");

        cmbOrtu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih kondisi-", "Bapak saja", "Ibu saja", "Bapak dan Ibu", "Bapak dan Ibu sudah meninggal" }));
        cmbOrtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrtuActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnTambahkan.setText("Tambahkan");
        btnTambahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahkanActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ahli Waris", "Jumlah", "Total bagian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        txtAnakLk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAnakLkKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnakLkKeyTyped(evt);
            }
        });

        txtAnakPrm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAnakPrmKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnakPrmKeyTyped(evt);
            }
        });

        ringkasanPanel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel6.setText("Suami");

        jLabel7.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel7.setText("Istri");

        jLabel9.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel9.setText("Ayah");

        jLabel10.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel10.setText("Ibu");

        jLabel11.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel11.setText("Anak laki-laki");

        jLabel13.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel13.setText("Anak perempuan");

        txIstri.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txIstri.setEnabled(false);

        txSuami.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txSuami.setEnabled(false);

        txAyah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txAyah.setEnabled(false);

        txIbu.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txIbu.setEnabled(false);

        txAnakLk.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txAnakLk.setEnabled(false);

        txAnakPrm.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txAnakPrm.setEnabled(false);

        jmlSuami.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jmlSuami.setText("0");

        jmlIstri.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jmlIstri.setText("0");

        jmlAyah.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jmlAyah.setText("0");

        jmlIbu.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jmlIbu.setText("0");

        jmlAnakLk.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jmlAnakLk.setText("0");

        jmlAnakPrm.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jmlAnakPrm.setText("0");

        javax.swing.GroupLayout ringkasanPanelLayout = new javax.swing.GroupLayout(ringkasanPanel);
        ringkasanPanel.setLayout(ringkasanPanelLayout);
        ringkasanPanelLayout.setHorizontalGroup(
            ringkasanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ringkasanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ringkasanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ringkasanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jmlIstri))
                    .addGroup(ringkasanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jmlSuami))
                    .addGroup(ringkasanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jmlAyah))
                    .addGroup(ringkasanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jmlIbu))
                    .addGroup(ringkasanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jmlAnakLk))
                    .addGroup(ringkasanPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jmlAnakPrm)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(ringkasanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txIstri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txSuami, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txAyah, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txIbu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txAnakLk, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txAnakPrm, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );
        ringkasanPanelLayout.setVerticalGroup(
            ringkasanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ringkasanPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ringkasanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txSuami, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ringkasanPanelLayout.createSequentialGroup()
                        .addGroup(ringkasanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jmlSuami))
                        .addGap(32, 32, 32)
                        .addGroup(ringkasanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txIstri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jmlIstri))
                        .addGap(29, 29, 29)
                        .addGroup(ringkasanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txAyah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jmlAyah))
                        .addGap(29, 29, 29)
                        .addGroup(ringkasanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txIbu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jmlIbu))
                        .addGap(29, 29, 29)
                        .addGroup(ringkasanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txAnakLk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jmlAnakLk))
                        .addGap(29, 29, 29)
                        .addGroup(ringkasanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txAnakPrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jmlAnakPrm))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ahliwarisPanelLayout = new javax.swing.GroupLayout(ahliwarisPanel);
        ahliwarisPanel.setLayout(ahliwarisPanelLayout);
        ahliwarisPanelLayout.setHorizontalGroup(
            ahliwarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ahliwarisPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ahliwarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(ahliwarisPanelLayout.createSequentialGroup()
                        .addGroup(ahliwarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ahliwarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ahliwarisPanelLayout.createSequentialGroup()
                                    .addComponent(btnKembali)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnHitung)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnTambahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addComponent(chkAnakLk))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(ahliwarisPanelLayout.createSequentialGroup()
                                .addComponent(rbHidup)
                                .addGap(60, 60, 60)
                                .addComponent(rbTidakHidup))
                            .addComponent(jLabel8)
                            .addGroup(ahliwarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbOrtu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ahliwarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAnakLk, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ahliwarisPanelLayout.createSequentialGroup()
                                        .addComponent(chkAnakPrm)
                                        .addGap(87, 87, 87)
                                        .addComponent(txtAnakPrm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ringkasanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        ahliwarisPanelLayout.setVerticalGroup(
            ahliwarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ahliwarisPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ahliwarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ahliwarisPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ahliwarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbHidup)
                            .addComponent(rbTidakHidup))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(ahliwarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkAnakLk)
                            .addComponent(txtAnakLk, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(ahliwarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAnakPrm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkAnakPrm))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cmbOrtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(ahliwarisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambahkan)
                            .addComponent(btnHitung)
                            .addComponent(btnReset)
                            .addComponent(btnKembali))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ahliwarisPanelLayout.createSequentialGroup()
                        .addComponent(ringkasanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );

        mainPanel.add(ahliwarisPanel, "card3");

        tentangPanel.setBackground(new java.awt.Color(255, 239, 159));
        tentangPanel.setMaximumSize(new java.awt.Dimension(680, 600));
        tentangPanel.setMinimumSize(new java.awt.Dimension(680, 600));
        tentangPanel.setPreferredSize(new java.awt.Dimension(710, 600));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("Cara Menggunakan Aplikasi");

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 239, 159));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("1. Pengguna mengisikan data dari pewaris yang berisi jenis kelamin, status pernikahan, dan \n    harta yang ditinggalkan oleh pewaris.\n2. Pengguna mengisikan data ahli waris yang masih hidup ketika pewaris telah meninggal.\n3. Pengguna klik tombol hitung untuk mendapatkan daftar yang menerima warisan \n    tersebut.\n4. Pengguna bisa menambahkan data yang telah dihitung ke tabel dengan mengklik tombol\n    tambahkan.\n5. Terima kasih");
        jTextArea2.setMaximumSize(new java.awt.Dimension(680, 600));
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout tentangPanelLayout = new javax.swing.GroupLayout(tentangPanel);
        tentangPanel.setLayout(tentangPanelLayout);
        tentangPanelLayout.setHorizontalGroup(
            tentangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tentangPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tentangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        tentangPanelLayout.setVerticalGroup(
            tentangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tentangPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(490, Short.MAX_VALUE))
        );

        mainPanel.add(tentangPanel, "card4");

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbMenikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMenikahActionPerformed
        // TODO add your handling code here:
        if (rbMenikah.isSelected())
            rbJomblo.setSelected(false);
    }//GEN-LAST:event_rbMenikahActionPerformed

    private void rbJombloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJombloActionPerformed
        // TODO add your handling code here:
        if (rbJomblo.isSelected())
            rbMenikah.setSelected(false);
    }//GEN-LAST:event_rbJombloActionPerformed

    private void jbtnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReset1ActionPerformed
        // TODO add your handling code here:
        rbPria.setSelected(false);
        rbWanita.setSelected(false);
        rbMenikah.setSelected(false);
        rbJomblo.setSelected(false);
        txtHartaWaris.setText(null);
    }//GEN-LAST:event_jbtnReset1ActionPerformed

    private void jbtnLanjut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLanjut1ActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //add
        mainPanel.add(ahliwarisPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jbtnLanjut1ActionPerformed

    private void rbHidupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHidupActionPerformed
        // TODO add your handling code here:
        if (rbHidup.isSelected()) {
            rbTidakHidup.setSelected(false);
        }
        if (rbHidup.isSelected()) {
            if (rbPria.isSelected()) {
                jmlIstri.setText("1");
            } else if (rbWanita.isSelected()) {
                jmlSuami.setText("1");
            }
        }
    }//GEN-LAST:event_rbHidupActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //add
        mainPanel.add(pewarisPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        rbHidup.setSelected(false);
        rbTidakHidup.setSelected(false);
        chkAnakLk.setSelected(false);
        chkAnakPrm.setSelected(false);
        cmbOrtu.setSelectedIndex(0);
        txtAnakLk.setText(null);
        txtAnakPrm.setText(null);
        jmlSuami.setText("0");
        jmlIstri.setText("0");
        jmlAyah.setText("0");
        jmlIbu.setText("0");
        jmlAnakLk.setText("0");
        jmlAnakPrm.setText("0");
        txSuami.setText(null);
        txIstri.setText(null);
        txAyah.setText(null);
        txIbu.setText(null);
        txAnakLk.setText(null);
        txAnakPrm.setText(null);

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        Warisan iWarisan = new Warisan();
        double ihartaWaris = 0;
        double iSuami, iIstri, iAyah, iIbu, iAnakLk, iAnakPrm, ashobah, hSuami, hIstri, hAyah, hIbu, hAnakLk, hAnakPrm;
        String strAyah, strIbu, strIstri, strSuami, strAnakLk, strAnakPrm;

        ihartaWaris = Double.parseDouble(txtHartaWaris.getText());
        iSuami = Double.parseDouble(jmlSuami.getText());
        iIstri = Double.parseDouble(jmlIstri.getText());
        iAyah = Double.parseDouble(jmlAyah.getText());
        iIbu = Double.parseDouble(jmlIbu.getText());
        iAnakLk = Double.parseDouble(jmlAnakLk.getText());
        iAnakPrm = Double.parseDouble(jmlAnakPrm.getText());

        iWarisan.setHartaWaris(ihartaWaris);
        iWarisan.setSuami(iSuami);
        iWarisan.setIstri(iIstri);
        iWarisan.setAyah(iAyah);
        iWarisan.setIbu(iIbu);
        iWarisan.setAnakLk(iAnakLk);
        iWarisan.setAnakPrm(iAnakPrm);

        if (rbPria.isSelected() && rbMenikah.isSelected()) {
            if (rbHidup.isSelected() && cmbOrtu.getSelectedItem().equals("Bapak dan Ibu")) {
                if (chkAnakLk.isSelected() && chkAnakPrm.isSelected()) {
                    ihartaWaris = iWarisan.getHartaWaris();
                    hSuami = 0;
                    hIstri = ihartaWaris * 1 / 8;
                    hAyah = ihartaWaris * 1 / 6;
                    hIbu = ihartaWaris * 1 / 6;
                    ashobah = (ihartaWaris - hSuami - hIstri - hAyah - hIbu) / iWarisan.getAnakLk() + iWarisan.getAnakPrm();
                    hAnakLk = ashobah * iAnakLk * 2;
                    hAnakPrm = iAnakPrm * ashobah;

                    strSuami = String.format("Rp%.2f", hSuami);
                    strIstri = String.format("Rp%.2f", hIstri);
                    strAyah = String.format("Rp%.2f", hAyah);
                    strIbu = String.format("Rp%.2f", hIbu);
                    strAnakLk = String.format("Rp%.2f", hAnakLk);
                    strAnakPrm = String.format("Rp%.2f", hAnakPrm);

                    txSuami.setText(strSuami);
                    txIstri.setText(strIstri);
                    txAyah.setText(strAyah);
                    txIbu.setText(strIbu);
                    txAnakLk.setText(strAnakLk);
                    txAnakPrm.setText(strAnakPrm);
                }
            }
        }
        if (rbPria.isSelected() && rbMenikah.isSelected()) {
            if (rbHidup.isSelected() && cmbOrtu.getSelectedItem().equals("Bapak saja")) {
                if (chkAnakLk.isSelected() && chkAnakPrm.isSelected()) {
                    ihartaWaris = iWarisan.getHartaWaris();
                    hSuami = 0;
                    hIstri = ihartaWaris * 1 / 8;
                    hAyah = ihartaWaris * 1 / 6;
                    hIbu = 0;
                    ashobah = (ihartaWaris - hSuami - hIstri - hAyah - hIbu) / iWarisan.getAnakLk() + iWarisan.getAnakPrm();
                    hAnakLk = ashobah * iAnakLk * 2;
                    hAnakPrm = iAnakPrm * ashobah;

                    strSuami = String.format("Rp%.2f", hSuami);
                    strIstri = String.format("Rp%.2f", hIstri);
                    strAyah = String.format("Rp%.2f", hAyah);
                    strIbu = String.format("Rp%.2f", hIbu);
                    strAnakLk = String.format("Rp%.2f", hAnakLk);
                    strAnakPrm = String.format("Rp%.2f", hAnakPrm);

                    txSuami.setText(strSuami);
                    txIstri.setText(strIstri);
                    txAyah.setText(strAyah);
                    txIbu.setText(strIbu);
                    txAnakLk.setText(strAnakLk);
                    txAnakPrm.setText(strAnakPrm);
                }
            }
        }
        if (rbPria.isSelected() && rbMenikah.isSelected()) {
            if (rbHidup.isSelected() && cmbOrtu.getSelectedItem().equals("Ibu saja")) {
                if (chkAnakLk.isSelected() && chkAnakPrm.isSelected()) {
                    ihartaWaris = iWarisan.getHartaWaris();
                    hSuami = 0;
                    hIstri = ihartaWaris * 1 / 8;
                    hAyah = 0;
                    hIbu = ihartaWaris * 1 / 6;
                    ashobah = (ihartaWaris - hSuami - hIstri - hAyah - hIbu) / iWarisan.getAnakLk() + iWarisan.getAnakPrm();
                    hAnakLk = ashobah * iAnakLk * 2;
                    hAnakPrm = iAnakPrm * ashobah;

                    strSuami = String.format("Rp%.2f", hSuami);
                    strIstri = String.format("Rp%.2f", hIstri);
                    strAyah = String.format("Rp%.2f", hAyah);
                    strIbu = String.format("Rp%.2f", hIbu);
                    strAnakLk = String.format("Rp%.2f", hAnakLk);
                    strAnakPrm = String.format("Rp%.2f", hAnakPrm);

                    txSuami.setText(strSuami);
                    txIstri.setText(strIstri);
                    txAyah.setText(strAyah);
                    txIbu.setText(strIbu);
                    txAnakLk.setText(strAnakLk);
                    txAnakPrm.setText(strAnakPrm);
                }
            }
        }
        if (rbPria.isSelected() && rbMenikah.isSelected()) {
            if (rbHidup.isSelected() && cmbOrtu.getSelectedItem().equals("Bapak dan Ibu sudah meninggal")) {
                if (chkAnakLk.isSelected() && chkAnakPrm.isSelected()) {
                    ihartaWaris = iWarisan.getHartaWaris();
                    hSuami = 0;
                    hIstri = ihartaWaris * 1 / 8;
                    hAyah = 0;
                    hIbu = 0;
                    ashobah = (ihartaWaris - hSuami - hIstri - hAyah - hIbu) / iWarisan.getAnakLk() + iWarisan.getAnakPrm();
                    hAnakLk = ashobah * iAnakLk * 2;
                    hAnakPrm = iAnakPrm * ashobah;

                    strSuami = String.format("Rp%.2f", hSuami);
                    strIstri = String.format("Rp%.2f", hIstri);
                    strAyah = String.format("Rp%.2f", hAyah);
                    strIbu = String.format("Rp%.2f", hIbu);
                    strAnakLk = String.format("Rp%.2f", hAnakLk);
                    strAnakPrm = String.format("Rp%.2f", hAnakPrm);

                    txSuami.setText(strSuami);
                    txIstri.setText(strIstri);
                    txAyah.setText(strAyah);
                    txIbu.setText(strIbu);
                    txAnakLk.setText(strAnakLk);
                    txAnakPrm.setText(strAnakPrm);
                }
            }
        }
        if (rbWanita.isSelected() && rbMenikah.isSelected()) {
            if (rbHidup.isSelected() && cmbOrtu.getSelectedItem().equals("Bapak dan Ibu")) {
                if (chkAnakLk.isSelected() && chkAnakPrm.isSelected()) {
                    ihartaWaris = iWarisan.getHartaWaris();
                    hSuami = ihartaWaris * 1 / 4;
                    hIstri = 0;
                    hAyah = ihartaWaris * 1 / 6;
                    hIbu = ihartaWaris * 1 / 6;
                    ashobah = (ihartaWaris - hSuami - hIstri - hAyah - hIbu) / iWarisan.getAnakLk() + iWarisan.getAnakPrm();
                    hAnakLk = ashobah * iAnakLk * 2;
                    hAnakPrm = iAnakPrm * ashobah;

                    strSuami = String.format("Rp%.2f", hSuami);
                    strIstri = String.format("Rp%.2f", hIstri);
                    strAyah = String.format("Rp%.2f", hAyah);
                    strIbu = String.format("Rp%.2f", hIbu);
                    strAnakLk = String.format("Rp%.2f", hAnakLk);
                    strAnakPrm = String.format("Rp%.2f", hAnakPrm);

                    txSuami.setText(strSuami);
                    txIstri.setText(strIstri);
                    txAyah.setText(strAyah);
                    txIbu.setText(strIbu);
                    txAnakLk.setText(strAnakLk);
                    txAnakPrm.setText(strAnakPrm);
                }
            }
        }
        if (rbWanita.isSelected() && rbMenikah.isSelected()) {
            if (rbHidup.isSelected() && cmbOrtu.getSelectedItem().equals("Bapak saja")) {
                if (chkAnakLk.isSelected() && chkAnakPrm.isSelected()) {
                    ihartaWaris = iWarisan.getHartaWaris();
                    hSuami = ihartaWaris * 1 / 4;
                    hIstri = 0;
                    hAyah = ihartaWaris * 1 / 6;
                    hIbu = 0;
                    ashobah = (ihartaWaris - hSuami - hIstri - hAyah - hIbu) / iWarisan.getAnakLk() + iWarisan.getAnakPrm();
                    hAnakLk = ashobah * iAnakLk * 2;
                    hAnakPrm = iAnakPrm * ashobah;

                    strSuami = String.format("Rp%.2f", hSuami);
                    strIstri = String.format("Rp%.2f", hIstri);
                    strAyah = String.format("Rp%.2f", hAyah);
                    strIbu = String.format("Rp%.2f", hIbu);
                    strAnakLk = String.format("Rp%.2f", hAnakLk);
                    strAnakPrm = String.format("Rp%.2f", hAnakPrm);

                    txSuami.setText(strSuami);
                    txIstri.setText(strIstri);
                    txAyah.setText(strAyah);
                    txIbu.setText(strIbu);
                    txAnakLk.setText(strAnakLk);
                    txAnakPrm.setText(strAnakPrm);
                }
            }
        }
        if (rbWanita.isSelected() && rbMenikah.isSelected()) {
            if (rbHidup.isSelected() && cmbOrtu.getSelectedItem().equals("Ibu saja")) {
                if (chkAnakLk.isSelected() && chkAnakPrm.isSelected()) {
                    ihartaWaris = iWarisan.getHartaWaris();
                    hSuami = ihartaWaris * 1 / 4;
                    hIstri = 0;
                    hAyah = 0;
                    hIbu = ihartaWaris * 1 / 6;
                    ashobah = (ihartaWaris - hSuami - hIstri - hAyah - hIbu) / iWarisan.getAnakLk() + iWarisan.getAnakPrm();
                    hAnakLk = ashobah * iAnakLk * 2;
                    hAnakPrm = iAnakPrm * ashobah;

                    strSuami = String.format("Rp%.2f", hSuami);
                    strIstri = String.format("Rp%.2f", hIstri);
                    strAyah = String.format("Rp%.2f", hAyah);
                    strIbu = String.format("Rp%.2f", hIbu);
                    strAnakLk = String.format("Rp%.2f", hAnakLk);
                    strAnakPrm = String.format("Rp%.2f", hAnakPrm);

                    txSuami.setText(strSuami);
                    txIstri.setText(strIstri);
                    txAyah.setText(strAyah);
                    txIbu.setText(strIbu);
                    txAnakLk.setText(strAnakLk);
                    txAnakPrm.setText(strAnakPrm);
                }
            }
        }
        if (rbWanita.isSelected() && rbMenikah.isSelected()) {
            if (rbHidup.isSelected() && cmbOrtu.getSelectedItem().equals("Bapak dan Ibu sudah meninggal")) {
                if (chkAnakLk.isSelected() && chkAnakPrm.isSelected()) {
                    ihartaWaris = iWarisan.getHartaWaris();
                    hSuami = ihartaWaris * 1 / 4;
                    hIstri = 0;
                    hAyah = 0;
                    hIbu = 0;
                    ashobah = (ihartaWaris - hSuami - hIstri - hAyah - hIbu) / iWarisan.getAnakLk() + iWarisan.getAnakPrm();
                    hAnakLk = ashobah * iAnakLk * 2;
                    hAnakPrm = iAnakPrm * ashobah;

                    strSuami = String.format("Rp%.2f", hSuami);
                    strIstri = String.format("Rp%.2f", hIstri);
                    strAyah = String.format("Rp%.2f", hAyah);
                    strIbu = String.format("Rp%.2f", hIbu);
                    strAnakLk = String.format("Rp%.2f", hAnakLk);
                    strAnakPrm = String.format("Rp%.2f", hAnakPrm);

                    txSuami.setText(strSuami);
                    txIstri.setText(strIstri);
                    txAyah.setText(strAyah);
                    txIbu.setText(strIbu);
                    txAnakLk.setText(strAnakLk);
                    txAnakPrm.setText(strAnakPrm);
                }
            }
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void jButtonInfoPewarisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInfoPewarisMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //add
        mainPanel.add(pewarisPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButtonInfoPewarisMouseClicked

    private void jButtonAhliWarisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAhliWarisMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //add
        mainPanel.add(ahliwarisPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButtonAhliWarisMouseClicked

    private void jButtonTentangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTentangMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //add
        mainPanel.add(tentangPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_jButtonTentangMouseClicked

    private void rbTidakHidupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTidakHidupActionPerformed
        // TODO add your handling code here:
        if (rbTidakHidup.isSelected()) {
            rbHidup.setSelected(false);
        }
        if (rbTidakHidup.isSelected()) {
            jmlIstri.setText("0");
            jmlSuami.setText("0");
        }
    }//GEN-LAST:event_rbTidakHidupActionPerformed

    private void rbPriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPriaActionPerformed
        // TODO add your handling code here:
        if (rbPria.isSelected())
            rbWanita.setSelected(false);
    }//GEN-LAST:event_rbPriaActionPerformed

    private void rbWanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWanitaActionPerformed
        // TODO add your handling code here:
        if (rbWanita.isSelected())
            rbPria.setSelected(false);
    }//GEN-LAST:event_rbWanitaActionPerformed

    private void cmbOrtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrtuActionPerformed
        // TODO add your handling code here:
        if (cmbOrtu.getSelectedItem().equals("Bapak saja")) {
            jmlAyah.setText("1");
            jmlIbu.setText("0");
        } else if (cmbOrtu.getSelectedItem().equals("Ibu saja")) {
            jmlAyah.setText("0");
            jmlIbu.setText("1");
        } else if (cmbOrtu.getSelectedItem().equals("Bapak dan Ibu")) {
            jmlAyah.setText("1");
            jmlIbu.setText("1");
        } else {
            jmlAyah.setText("0");
            jmlIbu.setText("0");
        }
    }//GEN-LAST:event_cmbOrtuActionPerformed

    private void btnTambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahkanActionPerformed
        // TODO add your handling code here:
        arrayTable();
    }//GEN-LAST:event_btnTambahkanActionPerformed

    private void txtAnakLkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnakLkKeyReleased
        // TODO add your handling code here:
        String in = txtAnakLk.getText();
        jmlAnakLk.setText(in);
    }//GEN-LAST:event_txtAnakLkKeyReleased

    private void txtAnakPrmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnakPrmKeyReleased
        // TODO add your handling code here:
        String in = txtAnakPrm.getText();
        jmlAnakPrm.setText(in);
    }//GEN-LAST:event_txtAnakPrmKeyReleased

    private void chkAnakLkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAnakLkActionPerformed
        // TODO add your handling code here:
        if (chkAnakLk.isSelected()) {
            txtAnakLk.setEnabled(true);
            txtAnakLk.setText("");
            txtAnakLk.requestFocus();
        } else{
            txtAnakLk.setEnabled(false);
            txtAnakLk.setText(null);
        }
    }//GEN-LAST:event_chkAnakLkActionPerformed

    private void txtAnakLkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnakLkKeyTyped
        // TODO add your handling code here:
        Warisan number = new Warisan();
        try {
            number.wajibAngka(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "Aplikasi Perhitungan Harta Waris");
        }
    }//GEN-LAST:event_txtAnakLkKeyTyped

    private void txtAnakPrmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnakPrmKeyTyped
        // TODO add your handling code here:
        Warisan number = new Warisan();
        try {
            number.wajibAngka(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "Aplikasi Perhitungan Harta Waris");
        }
    }//GEN-LAST:event_txtAnakPrmKeyTyped

    private void txtHartaWarisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHartaWarisKeyTyped
        // TODO add your handling code here:
        Warisan number = new Warisan();
        try {
            number.wajibAngka(evt);
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "Aplikasi Perhitungan Harta Waris");
        }
    }//GEN-LAST:event_txtHartaWarisKeyTyped

    private void chkAnakPrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAnakPrmActionPerformed
        // TODO add your handling code here:
        if (chkAnakPrm.isSelected()) {
            txtAnakPrm.setEnabled(true);
            txtAnakPrm.setText("");
            txtAnakPrm.requestFocus();
        } else{
            txtAnakPrm.setEnabled(false);
            txtAnakPrm.setText(null);
        }
    }//GEN-LAST:event_chkAnakPrmActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        JTextField notFill = null;
        for(Component x:ahliwarisPanel.getComponents()){
            if(x.getClass().toString().contains("javax.swing.JTextField")){
                notFill = (JTextField) x;
                notFill.setEnabled(false);
            }
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ahliwarisPanel;
    private javax.swing.JPanel body;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambahkan;
    private javax.swing.JCheckBox chkAnakLk;
    private javax.swing.JCheckBox chkAnakPrm;
    private javax.swing.JComboBox<String> cmbOrtu;
    private javax.swing.JButton jButtonAhliWaris;
    private javax.swing.JButton jButtonInfoPewaris;
    private javax.swing.JButton jButtonTentang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton jbtnLanjut1;
    private javax.swing.JButton jbtnReset1;
    private javax.swing.JLabel jmlAnakLk;
    private javax.swing.JLabel jmlAnakPrm;
    private javax.swing.JLabel jmlAyah;
    private javax.swing.JLabel jmlIbu;
    private javax.swing.JLabel jmlIstri;
    private javax.swing.JLabel jmlSuami;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel pewarisPanel;
    private javax.swing.JRadioButton rbHidup;
    private javax.swing.JRadioButton rbJomblo;
    private javax.swing.JRadioButton rbMenikah;
    private javax.swing.JRadioButton rbPria;
    private javax.swing.JRadioButton rbTidakHidup;
    private javax.swing.JRadioButton rbWanita;
    private javax.swing.JPanel ringkasanPanel;
    private javax.swing.JPanel tentangPanel;
    private javax.swing.JTextField txAnakLk;
    private javax.swing.JTextField txAnakPrm;
    private javax.swing.JTextField txAyah;
    private javax.swing.JTextField txIbu;
    private javax.swing.JTextField txIstri;
    private javax.swing.JTextField txSuami;
    private javax.swing.JTextField txtAnakLk;
    private javax.swing.JTextField txtAnakPrm;
    private javax.swing.JTextField txtHartaWaris;
    // End of variables declaration//GEN-END:variables
}
